/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import futbol.accesoADatos.EquipoData;
import javax.swing.JOptionPane;
import pojos.Equipos;

/**
 *
 * @author josel
 */
public class CargarEquipoVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form CargarEquipo
     */
    public CargarEquipoVista() {
        initComponents();
         jBActualizar.setEnabled(false);
         jBBorrar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTEmpatados = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jTTitulares = new javax.swing.JTextField();
        jTSuplentes = new javax.swing.JTextField();
        jTDT = new javax.swing.JTextField();
        jTPuntos = new javax.swing.JTextField();
        jTPartidosJugados = new javax.swing.JTextField();
        jTGanados = new javax.swing.JTextField();
        jTPerdidos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jBAgregar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBActualizar = new javax.swing.JButton();
        jBBorrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CARGAR EQUIPO");

        jLabel2.setText("NOMBRE");

        jLabel3.setText("TITULARES");

        jLabel4.setText("DT");

        jLabel5.setText("SUPLENTES");

        jLabel6.setText("PUNTOS");

        jLabel7.setText("PARTIDOS JUGADOS");

        jLabel8.setText("GANADOS");

        jLabel9.setText("EMPATADOS");

        jLabel10.setText("PERDIDOS");

        jBAgregar.setText("Agregar");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBActualizar.setText("Actualizar");
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });

        jBBorrar.setText("Borrar");
        jBBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTPerdidos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTTitulares, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTSuplentes, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTDT, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTPartidosJugados, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTGanados, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTEmpatados, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jBBuscar)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBAgregar)
                        .addGap(29, 29, 29)
                        .addComponent(jBActualizar)
                        .addGap(55, 55, 55)
                        .addComponent(jBBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jBBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTTitulares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTSuplentes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTPartidosJugados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTGanados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTEmpatados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPerdidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAgregar)
                    .addComponent(jBActualizar)
                    .addComponent(jBBorrar)
                    .addComponent(jButton1))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
      
        
         EquipoData ed = new EquipoData();
         Equipos eq=ed.buscarEquipo(jTNombre.getText());
         if(eq!=null){
           jBAgregar.setEnabled(false);
           jBActualizar.setEnabled(true);
            jBBorrar.setEnabled(true);
        jTNombre.setText(eq.getNombre());
        jTTitulares.setText(eq.getTitulares()+"");
        jTSuplentes.setText(eq.getTitulares()+"");
        jTDT.setText(eq.getDt());
        jTPuntos.setText(eq.getPuntos()+"");
        jTPartidosJugados.setText(eq.getPartidosJugados()+"");
        jTGanados.setText(eq.getGanados()+"");
        jTEmpatados.setText(eq.getEmpatados()+"");
        jTPerdidos.setText(eq.getPerdidos()+"");
         jTNombre.setEditable(false);
        }else{
            JOptionPane.showMessageDialog(this, "No hay equipo con ese nombre" );  
         }
        
        
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
     
         try {
            if (jTNombre.getText().isEmpty() || jTTitulares.getText().isEmpty() || jTSuplentes.getText().isEmpty() || jTDT.getText().isEmpty()
                    || jTPuntos.getText().isEmpty()||jTPartidosJugados.getText().isEmpty() ||jTGanados.getText().isEmpty()||jTEmpatados.getText().isEmpty()||jTPerdidos.getText().isEmpty()){

                JOptionPane.showMessageDialog(this, "Error: Uno o más campos están vacíos");

            } else {

                String nombre = jTNombre.getText();
                int titulares = Integer.parseInt(jTTitulares.getText());
                int suplentes = Integer.parseInt(jTSuplentes.getText());
                String dt =  jTDT.getText();
               int puntos = Integer.parseInt(jTPuntos.getText());
               int partjug = Integer.parseInt(jTPartidosJugados.getText());
               int ganados = Integer.parseInt(jTGanados.getText());
               int empatados = Integer.parseInt(jTEmpatados.getText());
               int perdidos = Integer.parseInt(jTPerdidos.getText());
               pojos.Equipos eq1=new pojos.Equipos(nombre, titulares, suplentes, dt, puntos, partjug, ganados, empatados, perdidos);
    
          
                EquipoData ed = new EquipoData();
                ed.crearEquipo(eq1);
                limpiar();
                this.dispose();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error en campo numerico -" + ex.getMessage());
        }
        
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
        
        try {
            if (jTNombre.getText().isEmpty() || jTTitulares.getText().isEmpty() || jTSuplentes.getText().isEmpty() || jTDT.getText().isEmpty()
                    || jTPuntos.getText().isEmpty()||jTPartidosJugados.getText().isEmpty() ||jTGanados.getText().isEmpty()||jTEmpatados.getText().isEmpty()||jTPerdidos.getText().isEmpty()){

                JOptionPane.showMessageDialog(this, "Error: Uno o más campos están vacíos");

            } else {

                String nombre = jTNombre.getText();
                int titulares = Integer.parseInt(jTTitulares.getText());
                int suplentes = Integer.parseInt(jTSuplentes.getText());
                String dt =  jTDT.getText();
               int puntos = Integer.parseInt(jTPuntos.getText());
               int partjug = Integer.parseInt(jTPartidosJugados.getText());
               int ganados = Integer.parseInt(jTGanados.getText());
               int empatados = Integer.parseInt(jTEmpatados.getText());
               int perdidos = Integer.parseInt(jTPerdidos.getText());
               pojos.Equipos eq1=new pojos.Equipos(nombre, titulares, suplentes, dt, puntos, partjug, ganados, empatados, perdidos);
    
          
                EquipoData ed = new EquipoData();
                ed.modificarEquipo(eq1);
                limpiar();
                this.dispose();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error en campo numerico -" + ex.getMessage());
        }
    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jBBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarActionPerformed
        
        try {
           

                String nombre = jTNombre.getText();
                int titulares = Integer.parseInt(jTTitulares.getText());
                int suplentes = Integer.parseInt(jTSuplentes.getText());
                String dt =  jTDT.getText();
               int puntos = Integer.parseInt(jTPuntos.getText());
               int partjug = Integer.parseInt(jTPartidosJugados.getText());
               int ganados = Integer.parseInt(jTGanados.getText());
               int empatados = Integer.parseInt(jTEmpatados.getText());
               int perdidos = Integer.parseInt(jTPerdidos.getText());
               pojos.Equipos eq1=new pojos.Equipos(nombre, titulares, suplentes, dt, puntos, partjug, ganados, empatados, perdidos);
    
          
                EquipoData ed = new EquipoData();
                ed.borrarEquipo(eq1);
                limpiar();
                this.dispose();
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error en campo numerico -" + ex.getMessage());
        }
                                               
        
    }//GEN-LAST:event_jBBorrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTDT;
    private javax.swing.JTextField jTEmpatados;
    private javax.swing.JTextField jTGanados;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTPartidosJugados;
    private javax.swing.JTextField jTPerdidos;
    private javax.swing.JTextField jTPuntos;
    private javax.swing.JTextField jTSuplentes;
    private javax.swing.JTextField jTTitulares;
    // End of variables declaration//GEN-END:variables

 private void limpiar() {
       
        jTNombre.setText("");
        jTTitulares.setText("");
        jTSuplentes.setText("");
        jTDT.setText("");
       jTPuntos.setText("");
        jTPartidosJugados.setText("");
        jTGanados.setText("");
        jTEmpatados.setText("");
       jTPerdidos.setText("");
        
      
    }
}
