/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import futbol.accesoADatos.EquipoData;
import javax.swing.table.DefaultTableModel;
import pojos.Equipos;

/**
 *
 * @author josel
 */
public class TablaDeEquiposVista extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };

    public TablaDeEquiposVista() {
        initComponents();
         armarCabecera();
        listarEquipos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTListaEquipos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(750, 350));
        setPreferredSize(new java.awt.Dimension(750, 350));

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("TABLA DE EQUIPOS");
        jTextField1.setPreferredSize(new java.awt.Dimension(208, 29));

        jTListaEquipos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTListaEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTListaEquipos.setMinimumSize(new java.awt.Dimension(750, 300));
        jTListaEquipos.setPreferredSize(new java.awt.Dimension(750, 300));
        jScrollPane1.setViewportView(jTListaEquipos);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jButton1)
                .addContainerGap(300, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButton1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTListaEquipos;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void listarEquipos() {
        EquipoData ed = new EquipoData();
        for (Equipos eq : ed.listarEquipos()) {
            modelo.addRow(new Object[]{
            eq.getNombre(),
            eq.getTitulares(),
            eq.getSuplentes(),
            eq.getDt(),
            eq.getPuntos(),
            eq.getPartidosJugados(),
            eq.getGanados(),
            eq.getEmpatados(),
            eq.getPerdidos()

        });
    }
}

private void armarCabecera() {
        modelo.addColumn("Nombre");
        modelo.addColumn("Titulares");
        modelo.addColumn("Suplentes");
        modelo.addColumn("DT");
        modelo.addColumn("Puntos");
        modelo.addColumn("Partidos Jugados");
        modelo.addColumn("Ganados");
        modelo.addColumn("Empatados");
        modelo.addColumn("Perdidos");
        
        jTListaEquipos.setModel(modelo);
    }

    private void borrarFilas() {
        int filas = jTListaEquipos.getRowCount() - 1;
        for (int f = filas; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }

}
